services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_global
    mem_limit: 256m
    mem_reservation: 64m
    cpus: 0.5
    restart: always
    env_file:
      - .env
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    networks:
      - mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # 🔥 init script if needed

networks:
  mariadb:
    name: mariadb
    driver: bridge

volumes:
  mariadb_data:
